pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }

    stages {

        stage('Start') {
            steps {
                sh 'echo "Pipeline Started Successfully!"'
            }
        }

        stage('Test Node Version') {
            steps {
                sh 'node --version'
            }
        }

        stage('Print Date') {
            steps {
                sh 'date'
            }
        }

        stage('List Files') {
            steps {
                sh 'ls -ltr'
            }
        }

        stage('Environment Info') {
            steps {
                sh 'echo "Current User: $(whoami)"'
                sh 'echo "Working Directory: $(pwd)"'
                sh 'echo "Hostname: $(hostname)"'
            }
        }

        stage('Sleep Demo') {
            steps {
                sh 'echo "Sleeping for 3 seconds..."'
                sh 'sleep 3'
                sh 'echo "Woke up!"'
            }
        }

        stage('Final Message') {
            steps {
                sh 'echo "All Stages Executed Successfully!"'
            }
        }

    }
}
